spring:
  application:
    name: libraryapi
# SPRING_PROFILES_ACTIVE=PRODUCTION
  profiles:
    active: production
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/library}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  springdoc:
    override-with-generic-response: false
   
logging:
  patter:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        paulojava_coffee: trace
    org:
      springframework:
        web: debug
        security: trace
        
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'
  
    
    # trace
    # debug
    # info
    # warn
    # error
    
    
# Production
---
    
spring:
  config:
    activate:
     on-profile: production
  jpa:
    show-sql: false
  
  
    
# Homolagacao
---
    
spring:
  config:
    activate:
     on-profile: Homolagacao
  jpa:
    show-sql: false
    
