spring:
  application:
    name: libraryapi
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTE_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  springdoc:
    override-with-generic-response: false
   
logging:
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        paulojava_coffee: trace
    org:
      springframework:
        web: debug
        security: trace
    
    # trace
    # debug
    # info
    # warn
    # error
   
    
